// Generated by gencpp from file gpg/detect_grasps.msg
// DO NOT EDIT!


#ifndef GPG_MESSAGE_DETECT_GRASPS_H
#define GPG_MESSAGE_DETECT_GRASPS_H

#include <ros/service_traits.h>


#include <gpg/detect_graspsRequest.h>
#include <gpg/detect_graspsResponse.h>


namespace gpg
{

struct detect_grasps
{

typedef detect_graspsRequest Request;
typedef detect_graspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detect_grasps
} // namespace gpg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gpg::detect_grasps > {
  static const char* value()
  {
    return "6544a7e3669d79f6069fe9d81fee1c1e";
  }

  static const char* value(const ::gpg::detect_grasps&) { return value(); }
};

template<>
struct DataType< ::gpg::detect_grasps > {
  static const char* value()
  {
    return "gpg/detect_grasps";
  }

  static const char* value(const ::gpg::detect_grasps&) { return value(); }
};


// service_traits::MD5Sum< ::gpg::detect_graspsRequest> should match
// service_traits::MD5Sum< ::gpg::detect_grasps >
template<>
struct MD5Sum< ::gpg::detect_graspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gpg::detect_grasps >::value();
  }
  static const char* value(const ::gpg::detect_graspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpg::detect_graspsRequest> should match
// service_traits::DataType< ::gpg::detect_grasps >
template<>
struct DataType< ::gpg::detect_graspsRequest>
{
  static const char* value()
  {
    return DataType< ::gpg::detect_grasps >::value();
  }
  static const char* value(const ::gpg::detect_graspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gpg::detect_graspsResponse> should match
// service_traits::MD5Sum< ::gpg::detect_grasps >
template<>
struct MD5Sum< ::gpg::detect_graspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gpg::detect_grasps >::value();
  }
  static const char* value(const ::gpg::detect_graspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpg::detect_graspsResponse> should match
// service_traits::DataType< ::gpg::detect_grasps >
template<>
struct DataType< ::gpg::detect_graspsResponse>
{
  static const char* value()
  {
    return DataType< ::gpg::detect_grasps >::value();
  }
  static const char* value(const ::gpg::detect_graspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPG_MESSAGE_DETECT_GRASPS_H
