// Generated by gencpp from file gpg/GripperInnerPoints.msg
// DO NOT EDIT!


#ifndef GPG_MESSAGE_GRIPPERINNERPOINTS_H
#define GPG_MESSAGE_GRIPPERINNERPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace gpg
{
template <class ContainerAllocator>
struct GripperInnerPoints_
{
  typedef GripperInnerPoints_<ContainerAllocator> Type;

  GripperInnerPoints_()
    : points()  {
    }
  GripperInnerPoints_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::gpg::GripperInnerPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpg::GripperInnerPoints_<ContainerAllocator> const> ConstPtr;

}; // struct GripperInnerPoints_

typedef ::gpg::GripperInnerPoints_<std::allocator<void> > GripperInnerPoints;

typedef boost::shared_ptr< ::gpg::GripperInnerPoints > GripperInnerPointsPtr;
typedef boost::shared_ptr< ::gpg::GripperInnerPoints const> GripperInnerPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpg::GripperInnerPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpg::GripperInnerPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpg::GripperInnerPoints_<ContainerAllocator1> & lhs, const ::gpg::GripperInnerPoints_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpg::GripperInnerPoints_<ContainerAllocator1> & lhs, const ::gpg::GripperInnerPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gpg::GripperInnerPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpg::GripperInnerPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpg::GripperInnerPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpg::GripperInnerPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpg::GripperInnerPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpg::GripperInnerPoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpg::GripperInnerPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::gpg::GripperInnerPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::gpg::GripperInnerPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpg/GripperInnerPoints";
  }

  static const char* value(const ::gpg::GripperInnerPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpg::GripperInnerPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The samples, as (x,y,z) points, 单个夹爪内部的点云列表\n"
"geometry_msgs/Point[] points\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gpg::GripperInnerPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpg::GripperInnerPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperInnerPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpg::GripperInnerPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpg::GripperInnerPoints_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPG_MESSAGE_GRIPPERINNERPOINTS_H
