// Generated by gencpp from file gpg/pointnet_gpd.msg
// DO NOT EDIT!


#ifndef GPG_MESSAGE_POINTNET_GPD_H
#define GPG_MESSAGE_POINTNET_GPD_H

#include <ros/service_traits.h>


#include <gpg/pointnet_gpdRequest.h>
#include <gpg/pointnet_gpdResponse.h>


namespace gpg
{

struct pointnet_gpd
{

typedef pointnet_gpdRequest Request;
typedef pointnet_gpdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pointnet_gpd
} // namespace gpg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gpg::pointnet_gpd > {
  static const char* value()
  {
    return "97ad4546f0b73d20321fdea3965e8519";
  }

  static const char* value(const ::gpg::pointnet_gpd&) { return value(); }
};

template<>
struct DataType< ::gpg::pointnet_gpd > {
  static const char* value()
  {
    return "gpg/pointnet_gpd";
  }

  static const char* value(const ::gpg::pointnet_gpd&) { return value(); }
};


// service_traits::MD5Sum< ::gpg::pointnet_gpdRequest> should match
// service_traits::MD5Sum< ::gpg::pointnet_gpd >
template<>
struct MD5Sum< ::gpg::pointnet_gpdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gpg::pointnet_gpd >::value();
  }
  static const char* value(const ::gpg::pointnet_gpdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpg::pointnet_gpdRequest> should match
// service_traits::DataType< ::gpg::pointnet_gpd >
template<>
struct DataType< ::gpg::pointnet_gpdRequest>
{
  static const char* value()
  {
    return DataType< ::gpg::pointnet_gpd >::value();
  }
  static const char* value(const ::gpg::pointnet_gpdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gpg::pointnet_gpdResponse> should match
// service_traits::MD5Sum< ::gpg::pointnet_gpd >
template<>
struct MD5Sum< ::gpg::pointnet_gpdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gpg::pointnet_gpd >::value();
  }
  static const char* value(const ::gpg::pointnet_gpdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpg::pointnet_gpdResponse> should match
// service_traits::DataType< ::gpg::pointnet_gpd >
template<>
struct DataType< ::gpg::pointnet_gpdResponse>
{
  static const char* value()
  {
    return DataType< ::gpg::pointnet_gpd >::value();
  }
  static const char* value(const ::gpg::pointnet_gpdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPG_MESSAGE_POINTNET_GPD_H
